### ISSUE TITLE
About BaGPipe-BGP configuration

### ISSUE THREAD

**Issue by glospoto** [Orange-OpenSource/bagpipe-bgp#3]
Hi all,
I'm trying to use BaGPipe in order to configure a Virtual Private Network (VPN) into a simulated network. That network has been realized creating several [docker](https://www.docker.com/) instances (acting as router) and linking those among them. An instance of [quagga](http://www.nongnu.org/quagga/) runs inside each docker instance, in order to act its as a router.
As far as I understood, BaGPipe-BGP is a routing deamon implementing BGP features related to VPN that should run on nodes in the networks that act as Provider Edge (PE), so I configured an instance of BaGPipe on each PE in my network, indicating into config/bgp.conf file:
- **local_address** the loopback IP address of the PE
- **peers** the loopback IP address of a remote PE.

The problem is that I always obtain a **Connection Refused** error. 

My question is: Did I correctly undestand the application of BaGPipe-BGP in order to set up a VPN? Moreover, did I correctly understand how to configure a BaGPipe-BGP instance? If it's so, could the problem be related to other mistakes? Thanks in advance.

Gabriele

**Comment by neromtee** [comment]
Hi Gabriele,

Sorry for the delay. I was off in the last two weeks.

The use case that you are trying to create with bagpipe-bgp makes sense.
The way you configure bagpipe-bgp ('local_address' for the address to use to originate connections, and 'peers' to specify BGP peers to initiate BGP sessions).

The error you see ("connection refused"), means that the peer is not listening on port 179.

If you are trying to create a peering between bagpipe-bgp  and bagpipe-bgp, this is normal: bagpipe-bgp does not listen for BGP connections, and only connects to remote peers (see https://github.com/Orange-OpenSource/bagpipe-bgp#caveats). This limitation was inherited from early version of exabgp, and some work would be required to let bagpipe-bgp leverage the ability to listen since introduced in exabgp.

If you want to create VPNs on multiple instances of bagipe-bgp, you need to add a BGP Route Reflector:
- one option is the fake route reflector in bagpipe-bgp, limited to two peers (https://github.com/Orange-OpenSource/bagpipe-bgp#bagpipe-fake-bgp-route-reflector)
- another option is openbsd bgpd (only for IPVPNs)
- another option is gobgp (didn't test myself, but documented at: https://github.com/osrg/gobgp/blob/master/docs/sources/evpn.md)
- quagga bgpd can possibly be made to work for IPVPNs (I tried but hit issues related to connection setup, that I did not invest time in resolving)

I hope this helps!

**Comment by glospoto** [comment]
Thanks a lot for your reply! 
I will follow your suggestions. I will try to use gobgp (I need to implement MPLS VPNs), and as far I understood bgpd is not suitable for this purpose.

Thanks again,
Gabriele

**Comment by tmmorin** [comment]
Your welcome. 
OpenBSD's bgpd is suitable as an IP VPN route reflector, but not (AFAIK) for E-VPN, but I didn't check very recently.
